# Generated by Django 6.0.5 on 2026-06-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_phone_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-customer override. Null = use store default.', max_digits=12, null=True, verbose_name='Credit Limit'),
        ),
    ]
