# Generated by Django 6.0.5 on 2026-05-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_balance_customer_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Vendorya platform-level admin. Bypasses per-store filtering via X-Store-ID header.', verbose_name='Super Admin'),
        ),
    ]
