# Generated by Django 6.0.5 on 2026-05-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Set when an admin issues a temp password. User must change it on next login.', verbose_name='Force Password Change'),
        ),
    ]
