# Generated by Django 6.0.5 on 2026-06-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_stock_transfer_and_credit_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_walk_in',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
