# Generated by Django 6.0.5 on 2026-06-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_pos_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store_credit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Refund credit the customer can spend in-store.', max_digits=12, verbose_name='Store Credit'),
        ),
    ]
