# Generated by Django 6.0.5 on 2026-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customer_gender_email_phone_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_prefs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
