# Generated by Django 6.0.5 on 2026-06-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_ui_prefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Opening-balance seed only. Live balance = customer_outstanding() (seed + invoice AR).', max_digits=12, verbose_name='Opening Balance (seed)'),
        ),
    ]
