# Generated by Django 6.0.8 on 2026-10-07 21:21

from django.db import migrations, models


def take_superadmins_out_of_shops(apps, schema_editor):
    # §PRIVACY-SUDO (s163): a platform account inside a shop reads that shop's data. Take every one out.
    User = apps.get_model('users', 'User')
    User.objects.filter(is_superadmin=True).update(store=None, default_branch=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text="Vendorya platform-level admin. Never belongs to a shop and never sees a shop's business data (§PRIVACY-SUDO).", verbose_name='Super Admin'),
        ),
        migrations.RunPython(take_superadmins_out_of_shops, migrations.RunPython.noop),
    ]
