# Generated by Django 6.0.5 on 2026-05-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('trial_length_days', models.PositiveIntegerField(default=14, help_text='Default trial length applied to new stores.')),
                ('grace_days', models.PositiveIntegerField(default=7, help_text='Days a PAST_DUE store keeps working before auto-suspend.')),
                ('invoice_due_days', models.PositiveIntegerField(default=7, help_text='Days after an invoice is issued before it counts as overdue.')),
                ('quota_mode', models.CharField(choices=[('BLOCK', 'Block — reject the action when over limit'), ('WARN', 'Warn — allow but flag when over limit'), ('OFF', 'Off — quotas stored but ignored')], default='WARN', help_text='How plan limits are enforced platform-wide.', max_length=10)),
                ('nightly_job_enabled', models.BooleanField(default=True, help_text='When off, run_billing_cycle exits without making changes.')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Stamped each time run_billing_cycle executes.', null=True)),
            ],
            options={
                'verbose_name': 'Billing Settings',
                'verbose_name_plural': 'Billing Settings',
            },
        ),
    ]
