# Generated by Django 6.0.5 on 2026-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsettings',
            name='nightly_job_enabled',
            field=models.BooleanField(default=False, help_text="When off, a scheduled run_billing_cycle exits without making changes. The manual 'Run now' button always works."),
        ),
    ]
