# Generated by Django 6.0.5 on 2026-06-13 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_storesettings_pos_double_print_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Human name, e.g. 'Zapier integration'.", max_length=120, verbose_name='Label')),
                ('key_prefix', models.CharField(db_index=True, help_text='Public, non-secret lookup prefix (shown in the UI).', max_length=32, unique=True, verbose_name='Key prefix')),
                ('key_hash', models.CharField(help_text='SHA-256 of the full raw key. The raw key is never stored.', max_length=64, verbose_name='Key hash')),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='Scopes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = never expires.', null=True, verbose_name='Expires at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last used')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.store')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='public_api__store_i_1f140a_idx')],
            },
        ),
    ]
