# Generated by Django 6.0.5 on 2026-05-29 10:31

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('SALE', 'Sale'), ('RETURN', 'Return'), ('DISCOUNT', 'Discount'), ('PURCHASE', 'Purchase'), ('ADJUSTMENT', 'Stock Adjustment'), ('EXPENSE', 'Expense'), ('SHIFT', 'Shift'), ('STAFF', 'Staff'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street_1', models.CharField(max_length=255, verbose_name='Street Address 1')),
                ('street_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(default='Egypt', max_length=100, verbose_name='Country')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Branch Name')),
                ('is_main_branch', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Short identifier. ISO if possible (EGP, USD, EUR) but free-form.', max_length=10, unique=True)),
                ('symbol', models.CharField(help_text="How it renders to the user. e.g. 'EGP', 'LE', '$', '€'.", max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('position', models.CharField(choices=[('PREFIX', 'Prefix (e.g. $100)'), ('SUFFIX', 'Suffix (e.g. 100 LE)')], default='SUFFIX', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Store Name')),
                ('store_code', models.CharField(blank=True, help_text='Globally unique 3-digit code — forms the first segment of every SKU in this store.', max_length=3, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Store code must be exactly 3 digits (000–999).')], verbose_name='Store Code')),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], default='FREE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('default_language', models.CharField(default='ar', max_length=5)),
                ('timezone', models.CharField(default='Africa/Cairo', help_text='IANA timezone for rendering dates/times to the store.', max_length=64)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='If False, POS will block sales when stock is insufficient.')),
                ('enable_agel_selling', models.BooleanField(default=True, help_text='Allow selling on credit (Customer Debt).')),
                ('decimals', models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places shown for prices/totals (0-4).')),
                ('thousands_separator', models.BooleanField(default=False, help_text='Show thousand separators in numbers (off by default).')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID / Betaka')),
                ('commercial_reg', models.CharField(blank=True, max_length=50, verbose_name='Commercial Reg / Sogel')),
                ('receipt_header', models.TextField(blank=True, help_text='Text to appear at the top of the receipt.', verbose_name='Receipt Header')),
                ('receipt_footer', models.TextField(blank=True, help_text='Text to appear at the bottom (e.g., Return Policy).', verbose_name='Receipt Footer')),
                ('product_numbering_mode', models.CharField(choices=[('PROGRESSIVE', 'Progressive (0001, 0002 …)'), ('RANDOM', 'Random (4-digit unique)')], default='PROGRESSIVE', max_length=20, verbose_name='Product Numbering Mode')),
                ('session_timeout_minutes', models.PositiveSmallIntegerField(default=0, help_text='Auto-logout after this many minutes idle. 0 = disabled. Enforced client-side.', verbose_name='Session Timeout (minutes)')),
                ('login_ip_allowlist', models.TextField(blank=True, help_text='Restrict OWNER/ADMIN logins to these IPs/CIDRs (comma or newline separated). Empty = no restriction.', verbose_name='Login IP Allowlist')),
                ('force_2fa_managers', models.BooleanField(default=False, help_text='Require TOTP two-factor auth for all staff with role Manager or higher.', verbose_name='Force 2FA for Managers+')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
    ]
