# Generated by Django 6.0.5 on 2026-05-29 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='store',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency used everywhere this store displays money.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='core.currency'),
        ),
        migrations.AddField(
            model_name='store',
            name='default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='store',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.store'),
        ),
        migrations.AddField(
            model_name='address',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.store'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.store'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='default_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.tax'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.store'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['store', '-timestamp'], name='core_activi_store_i_183e48_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['store', 'operation_type', '-timestamp'], name='core_activi_store_i_85f40d_idx'),
        ),
    ]
