# Generated by Django 6.0 on 2025-12-12 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        ('inventory', '0004_remove_product_attributes_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.category'),
        ),
    ]
