# Generated by Django 6.0.5 on 2026-05-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_store_contact_branch_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='field_visibility',
            field=models.JSONField(blank=True, default=dict, help_text='Per-role hidden columns: {table_id: {ROLE: [field, ...]}}. Server omits these fields from API responses for that role. Empty = use built-in defaults.', verbose_name='Field Visibility'),
        ),
    ]
