# Generated by Django 6.0.5 on 2026-06-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_storesettings_field_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Store logo for dark mode (recommended 480×112 px, PNG/SVG).', null=True, upload_to='store_logos/'),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_light',
            field=models.ImageField(blank=True, help_text='Store logo for light mode (recommended 480×112 px, PNG/SVG).', null=True, upload_to='store_logos/'),
        ),
    ]
