# Generated by Django 5.2.8 on 2026-01-02 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activitylog'),
        ('inventory', '0004_alter_productvariant_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='If False, POS will block sales when stock is insufficient.')),
                ('enable_agel_selling', models.BooleanField(default=True, help_text='Allow selling on credit (Customer Debt).')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID / Betaka')),
                ('commercial_reg', models.CharField(blank=True, max_length=50, verbose_name='Commercial Reg / Sogel')),
                ('receipt_header', models.TextField(blank=True, help_text='Text to appear at the top of the receipt.', verbose_name='Receipt Header')),
                ('receipt_footer', models.TextField(blank=True, help_text='Text to appear at the bottom (e.g., Return Policy).', verbose_name='Receipt Footer')),
                ('default_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.tax')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.store')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
    ]
