# Generated by Django 6.0.5 on 2026-05-27 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_storesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='operation_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('RETURN', 'Return'), ('DISCOUNT', 'Discount'), ('PURCHASE', 'Purchase'), ('ADJUSTMENT', 'Stock Adjustment'), ('EXPENSE', 'Expense'), ('SHIFT', 'Shift'), ('STAFF', 'Staff'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['store', '-timestamp'], name='core_activi_store_i_183e48_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['store', 'operation_type', '-timestamp'], name='core_activi_store_i_85f40d_idx'),
        ),
    ]
