# Generated by Django 6.0.5 on 2026-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_store_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='print_tax_id',
            field=models.BooleanField(default=True, help_text="When off, the Tax ID is omitted entirely from printed invoices (no 'N/A' placeholder). Turn off if the store is not tax-registered.", verbose_name='Print Tax ID on invoices'),
        ),
    ]
