# Generated by Django 6.0.5 on 2026-05-27 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activitylog_operation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Short identifier. ISO if possible (EGP, USD, EUR) but free-form.', max_length=10, unique=True)),
                ('symbol', models.CharField(help_text="How it renders to the user. e.g. 'EGP', 'LE', '$', '€'.", max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('position', models.CharField(choices=[('PREFIX', 'Prefix (e.g. $100)'), ('SUFFIX', 'Suffix (e.g. 100 LE)')], default='SUFFIX', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='store',
            name='timezone',
            field=models.CharField(default='Africa/Cairo', help_text='IANA timezone for rendering dates/times to the store.', max_length=64),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='decimals',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of decimal places shown for prices/totals (0-4).'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='thousands_separator',
            field=models.BooleanField(default=False, help_text='Show thousand separators in numbers (off by default).'),
        ),
        migrations.AddField(
            model_name='store',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency used everywhere this store displays money.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='core.currency'),
        ),
    ]
