# Generated by Django 6.0.5 on 2026-06-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_storesettings_print_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='credit_policy',
            field=models.CharField(choices=[('ALLOW', 'Allow — no enforcement'), ('WARN', 'Warn — allow but notify store owner'), ('BLOCK', 'Block — reject the sale')], default='ALLOW', max_length=5, verbose_name='Credit Policy'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='default_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max unpaid balance a customer may carry. Null = no limit.', max_digits=12, null=True, verbose_name='Default Credit Limit'),
        ),
    ]
