# Generated by Django 6.0.5 on 2026-06-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stock_transfer_and_credit_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='tax_enabled',
            field=models.BooleanField(default=True, help_text='Master switch. When off, sales charge no tax and POS hides the tax row — regardless of any product/default tax.'),
        ),
    ]
