# Generated by Django 6.0.5 on 2026-05-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_currencies_and_backfill_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='currency_symbol',
        ),
    ]
