# Generated by Django 6.0.5 on 2026-06-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_storesettings_pos_top_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='item_noun',
            field=models.CharField(choices=[('NAME', 'Name'), ('PRODUCT', 'Product'), ('ITEM', 'Item'), ('MODEL', 'Model')], default='NAME', help_text='Word used for a catalog item across the UI (display only).', max_length=10, verbose_name='Items are called'),
        ),
    ]
