# Generated by Django 6.0.5 on 2026-05-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_drop_store_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='force_2fa_managers',
            field=models.BooleanField(default=False, help_text='Require TOTP two-factor auth for all staff with role Manager or higher.', verbose_name='Force 2FA for Managers+'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='login_ip_allowlist',
            field=models.TextField(blank=True, help_text='Restrict OWNER/ADMIN logins to these IPs/CIDRs (comma or newline separated). Empty = no restriction.', verbose_name='Login IP Allowlist'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='session_timeout_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Auto-logout after this many minutes idle. 0 = disabled. Enforced client-side.', verbose_name='Session Timeout (minutes)'),
        ),
    ]
