# Generated by Django 6.0.5 on 2026-06-06 13:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_storesettings_item_noun'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='category_level_names',
            field=models.JSONField(default=core.models._default_category_levels, help_text='Display names for the 4 category tiers, e.g. Type / Category / Spec. Label only.', verbose_name='Category level names'),
        ),
    ]
