# Generated by Django 6.0.5 on 2026-06-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_storesettings_category_level_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address_line',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='store',
            name='fb_page',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Facebook Page'),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='Website'),
        ),
    ]
