# Generated by Django 6.0.5 on 2026-06-06 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_store_social_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('width_mm', models.PositiveSmallIntegerField(default=40)),
                ('height_mm', models.PositiveSmallIntegerField(default=20)),
                ('show_store_name', models.BooleanField(default=True)),
                ('show_product_name', models.BooleanField(default=True)),
                ('show_sku', models.BooleanField(default=True)),
                ('show_barcode', models.BooleanField(default=True)),
                ('show_price', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_presets', to='core.store')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
