# Generated by Django 6.0.5 on 2026-06-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_label_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='restocking_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default percentage deducted from a refund payout. 0 = none.', max_digits=5, verbose_name='Restocking Fee (%)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='return_window_days',
            field=models.PositiveIntegerField(default=0, help_text='Reject returns whose original invoice is older than this many days. 0 = no limit.', verbose_name='Return Window (days)'),
        ),
    ]
