# Generated by Django 6.0.5 on 2026-06-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_storesettings_restocking_fee_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='service_notify_hours',
            field=models.PositiveSmallIntegerField(default=1, help_text='Send ETA notification this many hours before the deadline. 0 = disabled.', verbose_name='Notify Before (hours)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='service_types',
            field=models.JSONField(blank=True, default=list, help_text='List of service type labels shown in the service form dropdown.', verbose_name='Service Types'),
        ),
    ]
