# Generated by Django 6.0.5 on 2026-06-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_storesettings_printer_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='pos_double_print_default',
            field=models.BooleanField(default=False, verbose_name='POS: 2x print by default'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='pos_print_default',
            field=models.BooleanField(default=True, verbose_name='POS: print receipt by default'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='srv_double_print_default',
            field=models.BooleanField(default=True, verbose_name='Service: 2x print by default'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='srv_print_default',
            field=models.BooleanField(default=True, verbose_name='Service: print receipt by default'),
        ),
    ]
