# Generated by Django 6.0.5 on 2026-06-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_storesettings_receipt_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='pos_cart_display_fields',
            field=models.JSONField(blank=True, default=list, help_text="Up to 4 fields shown under each line in the POS cart. Tokens: 'category' or 'attr:<attribute_key>'.", verbose_name='POS Cart Display Fields'),
        ),
    ]
