# Generated by Django 6.0.5 on 2026-06-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_storesettings_pos_cart_display_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='expired_sale_policy',
            field=models.CharField(choices=[('ALLOW', 'Allow — sell expired stock silently'), ('WARN', 'Warn — flag expired stock at POS but allow'), ('BLOCK', 'Block — reject a sale that would draw expired stock')], default='WARN', help_text='What happens when a FEFO draw would pull from an expired batch.', max_length=5, verbose_name='Expired-Stock Sale Policy'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='expiry_alert_days',
            field=models.PositiveIntegerField(default=60, help_text="Batches expiring within this many days are flagged 'expiring soon'.", verbose_name='Expiry Alert Window (days)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='expiry_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for pharmacy-grade expiry & batch (FEFO) tracking. Off = feature hidden; existing stores behave exactly as before.', verbose_name='Expiry / Batch Tracking'),
        ),
    ]
