# Generated by Django 6.0.5 on 2026-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_storesettings_expired_sale_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('GENERAL', 'General Retail'), ('PHARMACY', 'Pharmacy'), ('GROCERY', 'Grocery / Supermarket'), ('ELECTRONICS', 'Electronics / Devices'), ('CLOTHING', 'Clothing / Fashion')], default='GENERAL', help_text='Retail vertical. Seeds default capability switches at creation; never locks anything — owner can change every switch later.', max_length=20, verbose_name='Store Type'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='multi_unit_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for selling one product in multiple units (base + packs/strips). Off = only the base unit is offered; existing alternate units are hidden, not deleted.', verbose_name='Multi-Unit Selling'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='weight_selling_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for selling products by weight (per kg / 100g, decimal quantities). Off = feature hidden.', verbose_name='Weight-Based Selling'),
        ),
    ]
