# Generated by Django 6.0.5 on 2026-06-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_store_store_type_storesettings_multi_unit_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='default_alert_sound',
            field=models.CharField(default='s03', max_length=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='default_info_sound',
            field=models.CharField(default='s01', max_length=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='default_warning_sound',
            field=models.CharField(default='s02', max_length=10),
        ),
    ]
