# Generated by Django 6.0.5 on 2026-06-21 00:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_storesettings_default_alert_sound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='base_unit_name',
            field=models.CharField(default='pcs', help_text='Default name for a single base unit of stock (e.g. Pill, Tablet).', max_length=20, verbose_name='Quantity is called'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='unit_tier_names',
            field=models.JSONField(default=core.models._default_unit_tiers, help_text='Default names for the units above the base (e.g. Strip, Pack).', verbose_name='Unit tier names'),
        ),
    ]
