# Generated by Django 6.0.5 on 2026-06-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_storesettings_autocomplete_source_mb_auto_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='pos_clock_24h',
            field=models.BooleanField(default=True, help_text='POS topbar clock format: ON = 24-hour (13:05), OFF = 12-hour with AM/PM (1:05 PM).', verbose_name='POS 24-hour clock'),
        ),
    ]
