# Generated by Django 6.0.5 on 2026-07-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_storesettings_lockscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='pos_respect_mb_units',
            field=models.BooleanField(default=True, help_text='When ON, a product linked to a Memory Base drug auto-fills its Strip/Pack unit factors from the enriched packaging values.', verbose_name='POS respects Memory Base packaging'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='pos_tier_count',
            field=models.PositiveSmallIntegerField(default=3, help_text='Store-wide default number of POS selling tiers for multi-unit items. 3 = Pack+Strip+Unit, 2 = Pack+Strip. Pack (biggest) is always shown; overridable per product.', verbose_name='POS unit tiers'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='lock_facts_bank',
            field=models.JSONField(blank=True, default=list, help_text='List of {en, ar} fact objects rotated on the lock screen.', verbose_name='Lock Screen Facts Bank'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='lock_logo',
            field=models.ImageField(blank=True, help_text='Logo shown on the lock screen. PNG with transparency recommended.', null=True, upload_to='lock_logos/', verbose_name='Lock Screen Logo'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='lock_pin_hash',
            field=models.CharField(blank=True, help_text='Hashed lock-screen PIN (4–6 digits). Never exposed via API.', max_length=128, verbose_name='Lock Screen PIN (hashed)'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='lock_timeout_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Show a lock screen after this many minutes idle. 0 = disabled.', verbose_name='Lock Screen Timeout (minutes)'),
        ),
    ]
