# Generated by Django 6.0.5 on 2026-10-06 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_storesettings_pos_respect_mb_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='item_noun',
            field=models.CharField(default='NAME', help_text='Word used for a catalog item across the UI (display only).', max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]{1,10}$', "Use 1–10 letters, digits or '-' (no spaces).")], verbose_name='Items are called'),
        ),
    ]
