# Generated by Django 6.0.8 on 2026-10-07 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_item_noun_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='sku2_auto_new',
            field=models.BooleanField(default=False, help_text='Give every new product a SKU2 automatically.', verbose_name='SKU2 for new products'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sku2_digits',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(8)], verbose_name='SKU2 digits'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sku2_hide_search',
            field=models.BooleanField(default=False, help_text='Not shown in results — typing or scanning it still finds the product.', verbose_name='Hide SKU2 in search results'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sku2_hide_tables',
            field=models.BooleanField(default=False, verbose_name='Hide SKU2 in tables'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sku2_mode',
            field=models.CharField(choices=[('SEQUENCE', 'In sequence'), ('RANDOM', 'Random')], default='SEQUENCE', max_length=10, verbose_name='SKU2 numbering'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sku2_print_label',
            field=models.BooleanField(default=False, verbose_name='Print SKU2 on price stickers'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sku2_state',
            field=models.CharField(choices=[('OFF', 'Off'), ('ON', 'On'), ('DISABLED', 'Disabled for good')], default='OFF', max_length=10, verbose_name='SKU2 state'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sku_dashes',
            field=models.BooleanField(default=False, help_text='123-45-67 instead of 1234567. Dashes make two different SKUs impossible to look the same.', verbose_name='Dashes in SKU'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sku_product_digits',
            field=models.PositiveSmallIntegerField(choices=[(3, '3'), (4, '4'), (5, '5')], default=4, help_text='Width of the product number. It grows by one digit by itself when the numbers run out.', verbose_name='SKU product digits'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sku_shop_code',
            field=models.CharField(blank=True, default='', help_text='The shop part of every SKU. Empty = the store code.', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{2,3}$', 'Shop code must be 2 or 3 digits.')], verbose_name='SKU shop code'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='sku_supplier_digits',
            field=models.PositiveSmallIntegerField(choices=[(2, '2'), (3, '3')], default=3, help_text="Width of a NEW supplier's code. Grows by one digit when every code of this width is taken.", verbose_name='SKU supplier digits'),
        ),
    ]
