# Generated by Django 6.0.5 on 2026-05-29 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablePreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_id', models.CharField(help_text="Unique ID used by frontend (e.g., 'inventory_list')", max_length=100, verbose_name='Table ID')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_preferences', to='core.store')),
            ],
            options={
                'verbose_name': 'Table Preference',
                'verbose_name_plural': 'Table Preferences',
            },
        ),
    ]
