# Generated by Django 6.0.5 on 2026-05-30 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_storesettings_field_visibility'),
        ('smart_analysis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepreference',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuration'),
        ),
        migrations.AlterField(
            model_name='tablepreference',
            name='table_id',
            field=models.CharField(max_length=100, verbose_name='Table ID'),
        ),
        migrations.CreateModel(
            name='TablePreset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_id', models.CharField(max_length=100, verbose_name='Table ID')),
                ('name', models.CharField(max_length=100, verbose_name='Preset Name')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                ('is_default', models.BooleanField(default=False, help_text='Used for users without an explicit assignment.', verbose_name='Store Default')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_presets', to='core.store')),
            ],
            options={
                'verbose_name': 'Table Preset',
                'verbose_name_plural': 'Table Presets',
                'unique_together': {('store', 'table_id', 'name')},
            },
        ),
        migrations.AddField(
            model_name='tablepreference',
            name='assigned_preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='smart_analysis.tablepreset'),
        ),
    ]
