# Generated by Django 5.2.8 on 2025-12-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
        ('finance', '0001_initial'),
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='users.customer'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.store'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.salesinvoice'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.salesinvoice'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicesequence',
            unique_together={('store',)},
        ),
    ]
