# Generated by Django 6.0.5 on 2026-06-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_paymentmethod_is_agel'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
