# Generated by Django 5.2.8 on 2025-12-27 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        ('finance', '0003_payment_created_by_workshift'),
        ('inventory', '0002_alter_supplier_options_alter_supplier_code_prefix_and_more'),
        ('users', '0002_customer_balance_customer_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.PositiveIntegerField(editable=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_refunded', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.customer')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='finance.salesinvoice')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.store')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('restock_inventory', models.BooleanField(default=True, help_text='If True, adds item back to stock.')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.refundinvoice')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
            ],
        ),
    ]
