# Generated by Django 6.0.5 on 2026-06-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_line_discount_to_salesinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundinvoice',
            name='refund_method',
            field=models.CharField(choices=[('CASH', 'Cash / Original'), ('STORE_CREDIT', 'Store Credit')], default='CASH', max_length=15),
        ),
        migrations.AddField(
            model_name='refundinvoice',
            name='restocking_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
