# Generated by Django 6.0.5 on 2026-06-15 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_refundinvoice_refund_method_and_more'),
        ('inventory', '0008_default_storage_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.supplier'),
        ),
    ]
