# Generated by Django 6.0.5 on 2026-05-29 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_purchaseinvoice_purchaseitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refundinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='cost_at_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
