# Generated by Django 6.0.5 on 2026-05-29 06:03
from decimal import Decimal

from django.db import migrations
from django.db.models import Sum


def backfill_cost_at_sale(apps, schema_editor):
    """One-time backfill of cost_at_sale on existing POSTED sale lines.

    Uses the current weighted-average received purchase cost per variant. Exact
    cost-at-sale-date isn't recoverable for historical sales — this is the agreed
    approximation so COGS/profit reports have data from day one.
    """
    SalesInvoiceItem = apps.get_model('finance', 'SalesInvoiceItem')
    PurchaseItem = apps.get_model('finance', 'PurchaseItem')

    # Cache weighted-avg per (variant_id, store_id) to avoid recomputing per line.
    cache = {}

    items = (
        SalesInvoiceItem.objects
        .filter(invoice__status='POSTED')
        .select_related('variant', 'invoice')
    )
    for item in items.iterator():
        store_id = item.invoice.store_id
        key = (item.variant_id, store_id)
        if key not in cache:
            agg = PurchaseItem.objects.filter(
                variant_id=item.variant_id,
                invoice__store_id=store_id,
                invoice__status='RECEIVED',
                invoice__is_deleted=False,
            ).aggregate(total_cost=Sum('total_cost'), total_qty=Sum('quantity'))
            total_cost = agg['total_cost'] or Decimal('0')
            total_qty = agg['total_qty'] or Decimal('0')
            if total_qty > 0:
                cost = (total_cost / total_qty).quantize(Decimal('0.01'))
            else:
                cost = item.variant.cost_price or Decimal('0')
            cache[key] = cost
        item.cost_at_sale = cache[key]
        item.save(update_fields=['cost_at_sale'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_refundinvoice_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_cost_at_sale, noop_reverse),
    ]
