# Generated by Django 6.0.5 on 2026-06-15 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_storesettings_pos_cart_display_fields'),
        ('finance', '0006_purchase_supplier_nullable'),
        ('inventory', '0008_default_storage_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='draft_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_number',
            field=models.CharField(blank=True, default='', help_text='Our internal number (supplier prefix + running counter). Auto-filled when a supplier is set and left blank.', max_length=20, verbose_name='Purchase #'),
        ),
        migrations.CreateModel(
            name='PurchaseSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
            options={
                'unique_together': {('store', 'supplier')},
            },
        ),
    ]
