# Generated by Django 6.0.5 on 2026-06-19 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_purchaseinvoice_draft_items_and_more'),
        ('inventory', '0009_productunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productunit'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='unit_factor',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='refunditem',
            name='unit_factor',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productunit'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='unit_factor',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
    ]
