# Generated by Django 6.0.5 on 2026-06-19 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_purchaseitem_unit_purchaseitem_unit_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBatchConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cost_per_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
