# Generated by Django 6.0.5 on 2026-06-19 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_salebatchconsumption_purchaseitem_batch_number_and_more'),
        ('inventory', '0010_product_track_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebatchconsumption',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.stockbatch'),
        ),
        migrations.AddField(
            model_name='salebatchconsumption',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_consumptions', to='finance.salesinvoiceitem'),
        ),
    ]
