# Generated by Django 6.0.5 on 2026-10-06 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_supplierpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundinvoice',
            name='drawer_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='refundinvoice',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_refunds', to='finance.workshift'),
        ),
    ]
