# Generated by Django 6.0.5 on 2026-10-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_refund_drawer_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='checkout_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
    ]
