"""
Django settings for vendorya_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pl7)bjl-0ne1w#)v@*7(+$_59pfs@_qfl99)i$i-b=bi2ct#r3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['15.236.107.46', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',
    'django_extensions',
    

    # Third Party
    'rest_framework',
    'corsheaders',

    # Local Apps
    'import_export',
    'core',
    'users',
    'inventory',
    'finance',
    'smart_analysis',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vendorya_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vendorya_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'vendorya_db',
        'USER': 'mysqladmin',
        'PASSWORD': 'Mashakel1',
        'HOST': '15.236.107.46',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'
CORS_ALLOW_ALL_ORIGINS = True  # For development only

import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# JWT Settings
from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': '357327239995mashakelx2', # CHANGE THIS
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

JAZZMIN_SETTINGS = {
    # UI Customizer
    "site_title": "Vendorya ERP",
    "site_header": "Vendorya",
    "site_brand": "Vendorya",
    "welcome_sign": "Welcome to Vendorya ERP",
    "copyright": "Vendorya Ltd",
    "search_model": "users.Customer",

    # LOGOS
    "site_logo": "img/logo.png",
    "login_logo": "img/logo.png",
    "site_logo_classes": "img-circle",

    # Top Menu
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "POS (Coming Soon)", "url": "#", "new_window": True},
        {"model": "users.User"},
    ],

    # User Menu
    "usermenu_links": [
        {"name": "Support", "url": "#", "new_window": True},
        {"model": "users.User"}
    ],

    # Side Menu
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": ["inventory.ProductAttribute", "inventory.BundleItem"],

    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # Core
        "core.Store": "fas fa-store",
        "core.Branch": "fas fa-building",
        "core.Address": "fas fa-map-marker-alt",
        "core.ActivityLog": "fas fa-history", # NEW
        
        # Inventory
        "inventory.Product": "fas fa-tshirt",
        "inventory.ProductVariant": "fas fa-tags",
        "inventory.StockLevel": "fas fa-boxes",
        "inventory.StockAdjustment": "fas fa-wrench", # NEW
        "inventory.Category": "fas fa-sitemap",
        "inventory.Supplier": "fas fa-truck",
        "inventory.Tax": "fas fa-percent",
        "inventory.AttributeDefinition": "fas fa-list",
        
        # Finance
        "finance.WorkShift": "fas fa-clock", # NEW
        "finance.SalesInvoice": "fas fa-file-invoice-dollar",
        "finance.RefundInvoice": "fas fa-undo-alt", # NEW
        "finance.Payment": "fas fa-money-bill-wave",
        "finance.Expense": "fas fa-receipt",
        "finance.ExpenseCategory": "fas fa-folder-open",
        "finance.PaymentMethod": "fas fa-credit-card",
        "finance.InvoiceSequence": "fas fa-sort-numeric-up",
        
        # Users
        "users.Customer": "fas fa-user-tie",
        "users.User": "fas fa-user-shield",
    },

    # Sidebar Order
    "order_with_respect_to": [
        # Operations
        "finance.WorkShift",
        "finance.SalesInvoice",
        "finance.RefundInvoice",
        "finance.Payment",
        "finance.Expense",
        
        # Inventory
        "inventory.Product",
        "inventory.ProductVariant",
        "inventory.StockLevel",
        "inventory.StockAdjustment",
        
        # CRM
        "users.Customer",
        "inventory.Supplier",
        
        # Configuration
        "core.Store",
        "core.Branch",
        "inventory.Category",
        "inventory.Tax",
        "finance.PaymentMethod",
        
        # System
        "core.ActivityLog",
        "auth.User",
        "auth.Group",
    ],

    # UI Tweaks
    "related_modal_active": True,
    "custom_css": "css/admin_fix.css",
    "show_ui_builder": False,
}
X_FRAME_OPTIONS = 'SAMEORIGIN'