# Generated by Django 6.0.5 on 2026-06-07 20:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_storesettings_service_notify_hours_and_more'),
        ('finance', '0005_refundinvoice_refund_method_and_more'),
        ('users', '0008_customer_gender_email_phone_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(db_index=True, editable=False, max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('receive_date', models.DateField()),
                ('no_eta', models.BooleanField(default=True)),
                ('eta_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eta_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eta_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('info', models.TextField(blank=True)),
                ('keeping', models.CharField(blank=True, max_length=500)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], db_index=True, default='OPEN', max_length=10)),
                ('notify_bell', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='users.customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='finance.salesinvoice')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'status'], name='services_se_store_i_376d22_idx'), models.Index(fields=['store', 'eta_datetime'], name='services_se_store_i_40154b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
            options={
                'unique_together': {('store',)},
            },
        ),
    ]
