# Generated by Django 6.0.5 on 2026-06-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived'), ('RETURNED', 'Returned')], db_index=True, default='OPEN', max_length=10),
        ),
    ]
