# Generated by Django 6.0.5 on 2026-06-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_returned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
    ]
