# Generated by Django 6.0.5 on 2026-05-29 10:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_change', models.DecimalField(decimal_places=3, help_text='Use negative for loss (e.g., -1), positive for gain.', max_digits=10)),
                ('reason', models.CharField(choices=[('THEFT', 'Theft / Loss'), ('DAMAGE', 'Damage'), ('CORRECTION', 'Count Correction'), ('GIFT', 'Gift / Sample')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Supplier Name')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Contact Info')),
                ('code_prefix', models.CharField(help_text='Unique 3-digit code for this supplier within this store (100–999). Part of every SKU.', max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Prefix must be exactly 3 digits (100–999).')], verbose_name='Supplier Code Prefix')),
                ('prefix_locked', models.BooleanField(default=False, help_text='Once locked the prefix can never be changed — it is embedded in all SKUs.', verbose_name='Prefix Locked')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Tax Name')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rate %')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Display Name')),
                ('key', models.SlugField(verbose_name='Code Name')),
                ('input_type', models.CharField(choices=[('TEXT', 'Free Text'), ('SELECT', 'Dropdown Menu'), ('NUMBER', 'Number')], default='TEXT', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='core.store')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Category Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.store')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('product_type', models.CharField(choices=[('STANDARD', 'Standard Product'), ('SERVICE', 'Service (No Stock)'), ('BUNDLE', 'Bundle/Kit')], default='STANDARD', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='pcs', max_length=20, verbose_name='Unit')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.store')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'SKU must be exactly 10 digits.')], verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cost (Avg)')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Sell Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.attributedefinition')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='inventory.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_contents', to='inventory.product')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
            ],
        ),
    ]
