# Generated by Django 5.2.8 on 2025-12-21 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code_prefix',
            field=models.CharField(help_text='Unique 2-digit ID for generating product codes.', max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$', 'Prefix must be exactly 2 digits (00-99).')], verbose_name='Supplier Code Prefix'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('store', 'code_prefix')},
        ),
    ]
