# Generated by Django 5.2.8 on 2025-12-07 05:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        ('inventory', '0002_product_attributes_product_wholesale_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Display Name')),
                ('key', models.SlugField(verbose_name='Code Name')),
                ('input_type', models.CharField(choices=[('TEXT', 'Free Text'), ('SELECT', 'Dropdown Menu'), ('NUMBER', 'Number')], default='TEXT', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='core.store')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('store', 'key')},
            },
        ),
    ]
