# Generated by Django 5.2.8 on 2026-01-02 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z-]+$', 'SKU must be alphanumeric (A-Z, 0-9, -).')], verbose_name='SKU'),
        ),
    ]
