# Generated by Django 6.0.5 on 2026-06-03 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_transfer_and_credit_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delete_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='delete_reason',
            field=models.CharField(blank=True, choices=[('DISCONTINUED', 'Discontinued'), ('DUPLICATE', 'Duplicate'), ('MISTAKE', 'Created by mistake'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='hide_from_pos',
            field=models.BooleanField(default=False, help_text="Ghosted: stays in inventory and reports but won't appear in the POS catalog.", verbose_name='Hide from POS'),
        ),
    ]
