# Generated by Django 6.0.5 on 2026-06-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_delete_note_product_delete_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=5, help_text='Alert when on-hand stock falls to or below this. Default 5.', max_digits=12, verbose_name='Reorder Level'),
        ),
    ]
