# Generated by Django 6.0.5 on 2026-06-14 14:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_storesettings_receipt_controls'),
        ('inventory', '0006_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Storage Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='core.store')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('TO_STORAGE', 'To Storage'), ('FROM_STORAGE', 'From Storage'), ('WRITE_OFF', 'Write-Off')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cost_at_move', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_movements', to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_moves_out', to='core.branch')),
                ('related_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_movements', to='inventory.stockadjustment')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.storagelocation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_movements', to='core.store')),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_moves_in', to='core.branch')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_movements', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageStock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_remaining', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Qty Remaining')),
                ('cost_at_move', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cost Snapshot')),
                ('moved_in_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Moved In At')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layers', to='inventory.storagelocation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_stock', to='core.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_layers', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['moved_in_at'],
            },
        ),
    ]
