# Generated by Django 6.0.5 on 2026-06-19 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_default_storage_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Unit Name')),
                ('factor', models.DecimalField(decimal_places=3, help_text='How many base units this equals (Strip=10, Pack=30).', max_digits=12, verbose_name='Conversion Factor')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Sell Price')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_units', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
