# Generated by Django 6.0.5 on 2026-06-19 13:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_storesettings_expired_sale_policy_and_more'),
        ('finance', '0009_salebatchconsumption_purchaseitem_batch_number_and_more'),
        ('inventory', '0009_productunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_expiry',
            field=models.BooleanField(default=False, help_text='Stock this product as dated batches and sell earliest-expiry-first (FEFO).', verbose_name='Track Expiry / Batches'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='batch_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, default='', max_length=60, verbose_name='Batch / Lot No.')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('quantity_remaining', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('cost_per_base', models.DecimalField(decimal_places=2, default=0.0, help_text='True-FEFO COGS source: the cost of one base unit in this batch.', max_digits=12, verbose_name='Cost / base unit')),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='core.branch')),
                ('source_purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to='finance.purchaseitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='core.store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.productvariant')),
            ],
            options={
                'ordering': ['expiry_date', 'received_date'],
                'indexes': [models.Index(fields=['variant', 'branch', 'quantity_remaining'], name='inventory_s_variant_ff52ce_idx'), models.Index(fields=['store', 'expiry_date'], name='inventory_s_store_i_87a3d2_idx')],
            },
        ),
    ]
