# Generated by Django 6.0.5 on 2026-06-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_track_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selling_mode',
            field=models.CharField(choices=[('UNIT', 'By Unit (each)'), ('WEIGHT', 'By Weight (per kg)')], default='UNIT', max_length=10, verbose_name='Selling Mode'),
        ),
    ]
