# Generated by Django 6.0.5 on 2026-06-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_base_unit',
            field=models.BooleanField(default=True, help_text='Allow selling single base units (e.g. one pill) in POS. Stock is still counted in base units either way.', verbose_name='Sell by base unit'),
        ),
    ]
