# Generated by Django 6.0.5 on 2026-06-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_sell_base_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('THEFT', 'Theft / Loss'), ('DAMAGE', 'Damage'), ('CORRECTION', 'Count Correction'), ('GIFT', 'Gift / Sample'), ('OPENING', 'Opening / Initial Stock')], max_length=20),
        ),
    ]
