# Generated by Django 6.0.5 on 2026-06-27 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_stockadjustment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('STORE', 'Store Inventory'), ('MEMORY_BASE', 'Memory Base')], default='STORE', help_text='STORE = real sellable inventory; MEMORY_BASE = reference-pool entry (no supplier/SKU).', max_length=20, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'SKU must be exactly 10 digits.')], verbose_name='SKU'),
        ),
    ]
