# Generated by Django 6.0.5 on 2026-06-28 19:07

import django.db.models.deletion
import inventory.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_storesettings_pos_clock_24h'),
        ('inventory', '0016_product_name_trgm_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='showcase_autoplay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='showcase_lead',
            field=models.CharField(choices=[('video', 'Video first'), ('slideshow', 'Image slideshow')], default='video', max_length=10),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=8)),
                ('file', models.FileField(upload_to=inventory.models.product_media_upload_path)),
                ('poster', models.ImageField(blank=True, null=True, upload_to=inventory.models.product_media_upload_path)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inventory.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_media', to='core.store')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
