# Generated by Django 6.0.5 on 2026-06-29 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product_showcase_autoplay_product_showcase_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('strips_per_pack', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tablets_per_strip', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True)),
                ('indications', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('drug_interactions', models.TextField(blank=True)),
                ('enriched_at', models.DateTimeField(auto_now_add=True)),
                ('needs_review', models.BooleanField(default=False, help_text='Flagged by enrichment script for suspicious packaging values')),
                ('model_used', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='drug_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.drugprofile'),
        ),
    ]
