# Generated by Django 6.0.5 on 2026-07-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_drugprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='sellable',
            field=models.BooleanField(default=True, verbose_name='Sellable in POS'),
        ),
    ]
