# Generated by Django 6.0.8 on 2026-10-07 07:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_storesettings_sku2_auto_new_and_more'),
        ('inventory', '0019_productunit_sellable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sku2',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,8}$', 'SKU2 must be 1 to 8 digits.')], verbose_name='SKU2'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku_prefix',
            field=models.CharField(blank=True, default='', editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='store',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.store'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d+(-\\d+){0,2}$', 'SKU must be digits, optionally split by dashes.')], verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code_prefix',
            field=models.CharField(help_text='Unique code for this supplier within this store. Part of every SKU.', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{2,4}$', 'Supplier code must be 2 to 4 digits.')], verbose_name='Supplier Code Prefix'),
        ),
    ]
