# Generated by Django 6.0.5 on 2026-05-29 10:31

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', help_text='Auto-set to first user message if blank.', max_length=200)),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(help_text='Original document filename or URL.', max_length=255)),
                ('source_type', models.CharField(default='document', help_text="Loose tag: 'document', 'manual', 'url', etc.", max_length=20)),
                ('chunk_index', models.PositiveIntegerField(default=0, help_text='Position of this chunk inside its source document.')),
                ('content', models.TextField()),
                ('industries', models.JSONField(blank=True, default=list, help_text='List of industry tags for filtering. Empty = no industry filter.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
            ],
            options={
                'verbose_name': 'AI Knowledge Chunk',
                'verbose_name_plural': 'AI Knowledge Chunks',
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('MODEL', 'Model'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], db_index=True, max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of {kind, path, mime_type} entries for images / audio.')),
                ('tool_calls', models.JSONField(blank=True, default=list, help_text='Function calls the model issued on this turn (name + args + result).')),
                ('usage', models.JSONField(blank=True, default=dict, help_text='Token usage from the API: {input_tokens, output_tokens, ...}')),
            ],
            options={
                'verbose_name': 'AI Message',
                'verbose_name_plural': 'AI Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelCache',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_id', models.CharField(db_index=True, help_text="Gemini model name, e.g. 'gemini-2.5-flash'.", max_length=120, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('rpm', models.PositiveIntegerField(blank=True, help_text='Requests per minute.', null=True)),
                ('rpd', models.PositiveIntegerField(blank=True, help_text='Requests per day.', null=True)),
                ('tokens', models.PositiveIntegerField(blank=True, help_text='Token / TPM limit.', null=True)),
                ('supports_thinking', models.BooleanField(default=False)),
                ('supports_grounding', models.BooleanField(default=False)),
                ('supports_vision', models.BooleanField(default=False)),
                ('supports_audio', models.BooleanField(default=False)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model (cached)',
                'verbose_name_plural': 'AI Model Cache',
                'ordering': ['model_id'],
            },
        ),
        migrations.CreateModel(
            name='AIProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='ai_profile_avatars/')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only one profile can be active at a time.')),
                ('global_knowledge', models.BooleanField(default=True, help_text="If True, RAG queries the entire knowledge base. If False, only chunks tagged with this profile's industries.")),
                ('model_id', models.CharField(blank=True, default='', help_text='Matches AIModelCache.model_id. Blank = no model selected yet.', max_length=120)),
                ('vision_resolution', models.CharField(choices=[('AUTO', 'Auto'), ('LOW', 'Low'), ('HIGH', 'High')], default='AUTO', max_length=10)),
                ('max_output_tokens', models.PositiveIntegerField(blank=True, help_text='Blank = use model default.', null=True)),
                ('thinking_level', models.CharField(blank=True, choices=[('OFF', 'Off'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='OFF', max_length=10)),
                ('top_p', models.FloatField(blank=True, help_text='0.0 - 1.0. Blank = model default.', null=True)),
                ('top_k', models.PositiveIntegerField(blank=True, help_text='Blank = model default.', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='0.0 - 2.0. Blank = model default.', null=True)),
                ('google_grounding', models.BooleanField(default=False, help_text='Enable Google Search grounding (when model supports it).')),
                ('system_instruction', models.TextField(blank=True, default='', help_text='The persona prompt prepended to every conversation.')),
                ('enabled_tools', models.JSONField(blank=True, default=list, help_text='List of tool names enabled for this profile. Empty = all registered tools.')),
            ],
            options={
                'verbose_name': 'AI Profile',
                'verbose_name_plural': 'AI Profiles',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('gemini_api_key', models.CharField(blank=True, default='', max_length=200, verbose_name='Gemini API Key')),
            ],
            options={
                'verbose_name': 'AI Settings',
                'verbose_name_plural': 'AI Settings',
            },
        ),
    ]
