# Generated by Django 6.0.5 on 2026-06-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ai', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='extra_models',
            field=models.TextField(blank=True, default='', help_text="Force these model ids into the dropdown even if auto-discovery would skip them (must still exist in Google's live list). One per line.", verbose_name='Extra models to include'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='hidden_models',
            field=models.TextField(blank=True, default='', help_text='Hide these model ids from the dropdown. Substring match. One per line.', verbose_name='Models to hide'),
        ),
    ]
