# Generated by Django 6.0.5 on 2026-06-13 10:41

import core.encryption
from django.db import migrations


def encrypt_existing_key(apps, schema_editor):
    """Encrypt any pre-existing plaintext key in place. Re-saving the row runs
    EncryptedCharField.get_prep_value, which encrypts (and is idempotent)."""
    AISettings = apps.get_model('admin_ai', 'AISettings')
    for row in AISettings.objects.all():
        if row.gemini_api_key:
            row.save(update_fields=['gemini_api_key'])


def noop_reverse(apps, schema_editor):
    """No clean reverse — ciphertext stays encrypted; the field still reads it."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ai', '0004_aisettings_extra_models_aisettings_hidden_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='gemini_api_key',
            field=core.encryption.EncryptedCharField(blank=True, default='', max_length=512, verbose_name='Gemini API Key'),
        ),
        migrations.RunPython(encrypt_existing_key, noop_reverse),
    ]
