# Generated by Django 6.0.5 on 2026-05-27 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_activitylog_operation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BILLING_INVOICE', 'Billing Invoice'), ('BILLING_PAID', 'Payment Received'), ('SUBSCRIPTION', 'Subscription'), ('LOW_STOCK', 'Low Stock'), ('SHIFT_DIFFERENCE', 'Shift Difference'), ('SYSTEM', 'System'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Frontend route the bell click should open.', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['store', '-created_at'], name='notificatio_store_i_84d170_idx'), models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
