# Generated by Django 6.0.5 on 2026-05-29 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_enabled', models.BooleanField(default=True)),
                ('warning_enabled', models.BooleanField(default=True)),
                ('alert_enabled', models.BooleanField(default=True)),
                ('info_sound', models.CharField(choices=[('mute', 'Mute'), ('s01', 'Sound 01'), ('s02', 'Sound 02'), ('s03', 'Sound 03'), ('s04', 'Sound 04'), ('s05', 'Sound 05'), ('s06', 'Sound 06'), ('s07', 'Sound 07'), ('s08', 'Sound 08'), ('s09', 'Sound 09'), ('s10', 'Sound 10')], default='s01', max_length=10)),
                ('warning_sound', models.CharField(choices=[('mute', 'Mute'), ('s01', 'Sound 01'), ('s02', 'Sound 02'), ('s03', 'Sound 03'), ('s04', 'Sound 04'), ('s05', 'Sound 05'), ('s06', 'Sound 06'), ('s07', 'Sound 07'), ('s08', 'Sound 08'), ('s09', 'Sound 09'), ('s10', 'Sound 10')], default='s02', max_length=10)),
                ('alert_sound', models.CharField(choices=[('mute', 'Mute'), ('s01', 'Sound 01'), ('s02', 'Sound 02'), ('s03', 'Sound 03'), ('s04', 'Sound 04'), ('s05', 'Sound 05'), ('s06', 'Sound 06'), ('s07', 'Sound 07'), ('s08', 'Sound 08'), ('s09', 'Sound 09'), ('s10', 'Sound 10')], default='s03', max_length=10)),
                ('admin_sound', models.CharField(choices=[('mute', 'Mute'), ('s01', 'Sound 01'), ('s02', 'Sound 02'), ('s03', 'Sound 03'), ('s04', 'Sound 04'), ('s05', 'Sound 05'), ('s06', 'Sound 06'), ('s07', 'Sound 07'), ('s08', 'Sound 08'), ('s09', 'Sound 09'), ('s10', 'Sound 10')], default='s01', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ALERT', 'Alert'), ('ADMIN', 'Admin Note')], db_index=True, default='INFO', max_length=10)),
                ('type', models.CharField(choices=[('BILLING_INVOICE', 'Billing Invoice'), ('BILLING_PAID', 'Payment Received'), ('SUBSCRIPTION', 'Subscription'), ('LOW_STOCK', 'Low Stock'), ('SHIFT_DIFFERENCE', 'Shift Difference'), ('INVOICE_VOIDED', 'Invoice Voided'), ('ADMIN_NOTE', 'Admin Note'), ('SYSTEM', 'System'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Frontend route the bell click should open.', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
