# Generated by Django 6.0.5 on 2026-05-29 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_storesettings_force_2fa_managers_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_enabled', models.BooleanField(default=True)),
                ('warning_enabled', models.BooleanField(default=True)),
                ('alert_enabled', models.BooleanField(default=True)),
                ('info_sound', models.CharField(choices=[('mute', 'Mute'), ('s01', 'Sound 01'), ('s02', 'Sound 02'), ('s03', 'Sound 03'), ('s04', 'Sound 04'), ('s05', 'Sound 05'), ('s06', 'Sound 06'), ('s07', 'Sound 07'), ('s08', 'Sound 08'), ('s09', 'Sound 09'), ('s10', 'Sound 10')], default='s01', max_length=10)),
                ('warning_sound', models.CharField(choices=[('mute', 'Mute'), ('s01', 'Sound 01'), ('s02', 'Sound 02'), ('s03', 'Sound 03'), ('s04', 'Sound 04'), ('s05', 'Sound 05'), ('s06', 'Sound 06'), ('s07', 'Sound 07'), ('s08', 'Sound 08'), ('s09', 'Sound 09'), ('s10', 'Sound 10')], default='s02', max_length=10)),
                ('alert_sound', models.CharField(choices=[('mute', 'Mute'), ('s01', 'Sound 01'), ('s02', 'Sound 02'), ('s03', 'Sound 03'), ('s04', 'Sound 04'), ('s05', 'Sound 05'), ('s06', 'Sound 06'), ('s07', 'Sound 07'), ('s08', 'Sound 08'), ('s09', 'Sound 09'), ('s10', 'Sound 10')], default='s03', max_length=10)),
                ('admin_sound', models.CharField(choices=[('mute', 'Mute'), ('s01', 'Sound 01'), ('s02', 'Sound 02'), ('s03', 'Sound 03'), ('s04', 'Sound 04'), ('s05', 'Sound 05'), ('s06', 'Sound 06'), ('s07', 'Sound 07'), ('s08', 'Sound 08'), ('s09', 'Sound 09'), ('s10', 'Sound 10')], default='s01', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ALERT', 'Alert'), ('ADMIN', 'Admin Note')], db_index=True, default='INFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BILLING_INVOICE', 'Billing Invoice'), ('BILLING_PAID', 'Payment Received'), ('SUBSCRIPTION', 'Subscription'), ('LOW_STOCK', 'Low Stock'), ('SHIFT_DIFFERENCE', 'Shift Difference'), ('INVOICE_VOIDED', 'Invoice Voided'), ('ADMIN_NOTE', 'Admin Note'), ('SYSTEM', 'System'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['store', 'priority', '-created_at'], name='notificatio_store_i_7b479f_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL),
        ),
    ]
