# Generated by Django 6.0.5 on 2026-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BILLING_INVOICE', 'Billing Invoice'), ('BILLING_PAID', 'Payment Received'), ('SUBSCRIPTION', 'Subscription'), ('LOW_STOCK', 'Low Stock'), ('EXPIRY', 'Expiring / Expired Stock'), ('SHIFT_DIFFERENCE', 'Shift Difference'), ('INVOICE_VOIDED', 'Invoice Voided'), ('ADMIN_NOTE', 'Admin Note'), ('SYSTEM', 'System'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=30),
        ),
    ]
