# Generated by Django 6.0.5 on 2026-06-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSoundConfig',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('admin_sound', models.CharField(choices=[('mute', 'Mute'), ('s01', 'Sound 01'), ('s02', 'Sound 02'), ('s03', 'Sound 03'), ('s04', 'Sound 04'), ('s05', 'Sound 05'), ('s06', 'Sound 06'), ('s07', 'Sound 07'), ('s08', 'Sound 08'), ('s09', 'Sound 09'), ('s10', 'Sound 10')], default='s01', max_length=10)),
            ],
            options={
                'verbose_name': 'Admin notification sound',
            },
        ),
    ]
